version: "3.9"
    
services:
  app:
    build: .
    image: app:tag
    ports:
      - "8080:8080"
    restart: always
    environment:
      #DEBUG: 1
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      RABBIT_HOST: rabbitmq
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_USER: elastic
      ELASTICSEARCH_PASSWORD: elastic

  db:
    image: mysql:8
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somepass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app  
  
  rabbitmq:
    image: rabbitmq:3
    restart: always

  elasticsearch:
    image: elasticsearch:7.14.2
    restart: always
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      ELASTIC_PASSWORD: "elastic"
      xpack.security.enabled: "true"
  
  kibana:
    image: kibana:7.14.2
    ports:
      - "5601:5601"
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTIC_PASSWORD: elastic
      ELASTICSEARCH_USERNAME: elastic
